sonar.projectKey=PlatformRelay_MKurator
sonar.organization=platformrelay
sonar.projectName=MKurator
sonar.sources=.
sonar.exclusions=**/zz_generated.*,**/vendor/**,**/charts/**,**/hack/**,**/config/**,**/test/mocks/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/api/**,**/cmd/**,**/test/**
