// Command crd-ref-gen renders per-CRD field reference tables from the committed
// CRD OpenAPI schemas (config/crd/bases/*.yaml) into the hand-authored per-kind
// pages under docs/crds/. It only touches content between the markers
//
//	<!-- crd-ref:begin KIND -->
//	<!-- crd-ref:end -->
//
// so the surrounding prose (intro, examples, MQSC mapping) stays hand-owned.
// Output is deterministic (fields sorted) so `task verify` can gate drift.
//
// Usage: go run ./hack/tools/crd-ref-gen [--crd-dir DIR] [--docs-dir DIR]
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

// hubVersion is the API version documented in the reference tables.
const hubVersion = "v1beta1"

// typeObject is the rendered type for a structured object field.
const typeObject = "object"

// genNotice heads every generated block so hand-editors know to run the task.
const genNotice = "<!-- Generated by hack/tools/crd-ref-gen; do not edit. Run `task docs:crd-ref`. -->"

var (
	beginRe = regexp.MustCompile(`(?m)^<!-- crd-ref:begin ([A-Za-z0-9]+) -->$`)
	endMark = "<!-- crd-ref:end -->"
	wsRe    = regexp.MustCompile(`\s+`)
)

func main() {
	crdDir := flag.String("crd-dir", "config/crd/bases", "directory holding CRD YAML")
	docsDir := flag.String("docs-dir", "docs/crds", "directory holding per-kind reference pages")
	flag.Parse()

	if err := run(*crdDir, *docsDir); err != nil {
		fmt.Fprintln(os.Stderr, "crd-ref-gen:", err)
		os.Exit(1)
	}
}

func run(crdDir, docsDir string) error {
	crds, err := filepath.Glob(filepath.Join(crdDir, "*.yaml"))
	if err != nil {
		return err
	}
	// Index generated tables by kind so page lookup is not name-coupled.
	byKind := map[string]string{}
	for _, path := range crds {
		raw, rerr := os.ReadFile(path) //nolint:gosec // repo-local CRD path from a fixed glob
		if rerr != nil {
			return rerr
		}
		var crd apiextv1.CustomResourceDefinition
		if uerr := yaml.Unmarshal(raw, &crd); uerr != nil {
			return fmt.Errorf("%s: %w", path, uerr)
		}
		schema := hubSchema(&crd)
		if schema == nil {
			continue
		}
		byKind[crd.Spec.Names.Kind] = renderKind(&crd, schema)
	}

	pages, err := filepath.Glob(filepath.Join(docsDir, "*.md"))
	if err != nil {
		return err
	}
	sort.Strings(pages)
	injected := 0
	for _, page := range pages {
		raw, rerr := os.ReadFile(page) //nolint:gosec // repo-local docs path from a fixed glob
		if rerr != nil {
			return rerr
		}
		out, did, ierr := inject(string(raw), byKind)
		if ierr != nil {
			return fmt.Errorf("%s: %w", page, ierr)
		}
		if did {
			if werr := os.WriteFile(page, []byte(out), 0o600); werr != nil {
				return werr
			}
			injected++
			fmt.Println("crd-ref-gen: updated", page)
		}
	}
	if injected == 0 {
		fmt.Println("crd-ref-gen: no pages with crd-ref markers (nothing to do)")
	}
	return nil
}

// hubSchema returns the openAPIV3Schema for the hub version, or nil.
func hubSchema(crd *apiextv1.CustomResourceDefinition) *apiextv1.JSONSchemaProps {
	for i := range crd.Spec.Versions {
		v := crd.Spec.Versions[i]
		if v.Name == hubVersion && v.Schema != nil {
			return v.Schema.OpenAPIV3Schema
		}
	}
	return nil
}

// inject replaces the body of each `crd-ref:begin KIND` … `crd-ref:end` block
// with the generated table for KIND. Returns whether anything changed.
func inject(src string, byKind map[string]string) (string, bool, error) {
	var b strings.Builder
	changed := false
	rest := src
	for {
		loc := beginRe.FindStringSubmatchIndex(rest)
		if loc == nil {
			b.WriteString(rest)
			break
		}
		kind := rest[loc[2]:loc[3]]
		beginLine := rest[loc[0]:loc[1]]
		b.WriteString(rest[:loc[0]])
		b.WriteString(beginLine)
		b.WriteString("\n")

		after := rest[loc[1]:]
		endIdx := strings.Index(after, endMark)
		if endIdx < 0 {
			return "", false, fmt.Errorf("crd-ref:begin %s without matching crd-ref:end", kind)
		}
		table, ok := byKind[kind]
		if !ok {
			return "", false, fmt.Errorf("no CRD schema found for kind %q", kind)
		}
		b.WriteString(table)
		b.WriteString(endMark)
		changed = true
		rest = after[endIdx+len(endMark):]
	}
	return b.String(), changed, nil
}

func renderKind(crd *apiextv1.CustomResourceDefinition, schema *apiextv1.JSONSchemaProps) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", genNotice)
	fmt.Fprintf(&b, "API version: `%s/%s` · Kind: `%s`\n\n",
		crd.Spec.Group, hubVersion, crd.Spec.Names.Kind)
	for _, sec := range []string{"spec", "status"} {
		sub, ok := schema.Properties[sec]
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "### `.%s`\n\n", sec)
		b.WriteString("| Field | Type | Required | Description |\n")
		b.WriteString("| --- | --- | --- | --- |\n")
		b.WriteString(renderProps("", &sub))
		b.WriteString("\n")
	}
	return b.String()
}

// renderProps emits one table row per field, flattening non-array object fields
// a single level with dotted names. Deterministic: fields are sorted.
func renderProps(prefix string, node *apiextv1.JSONSchemaProps) string {
	names := make([]string, 0, len(node.Properties))
	for name := range node.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	required := map[string]bool{}
	for _, r := range node.Required {
		required[r] = true
	}
	var b strings.Builder
	for _, name := range names {
		f := node.Properties[name]
		full := name
		if prefix != "" {
			full = prefix + "." + name
		}
		req := "no"
		if required[name] {
			req = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
			full, typeOf(&f), req, oneLine(f.Description))
		// Flatten one level of nested (non-array) objects with named properties.
		if prefix == "" && f.Type == "object" && len(f.Properties) > 0 {
			b.WriteString(renderProps(full, &f))
		}
	}
	return b.String()
}

// typeOf renders a human-readable type for a schema node.
func typeOf(s *apiextv1.JSONSchemaProps) string {
	if len(s.Enum) > 0 {
		vals := make([]string, 0, len(s.Enum))
		for _, e := range s.Enum {
			var v any
			if err := json.Unmarshal(e.Raw, &v); err == nil {
				vals = append(vals, fmt.Sprintf("%v", v))
			}
		}
		return "enum(" + strings.Join(vals, ", ") + ")"
	}
	switch s.Type {
	case "array":
		if s.Items != nil && s.Items.Schema != nil {
			return "[]" + typeOf(s.Items.Schema)
		}
		return "array"
	case "object":
		if s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil {
			return "map[string]" + typeOf(s.AdditionalProperties.Schema)
		}
		return typeObject
	case "":
		return typeObject
	default:
		return s.Type
	}
}

// oneLine collapses whitespace and escapes table-breaking characters.
func oneLine(s string) string {
	s = wsRe.ReplaceAllString(strings.TrimSpace(s), " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	if s == "" {
		return "—"
	}
	return s
}
